### ISSUE TITLE
Option to use devel branch of Bioconductor

### ISSUE THREAD

**Issue by PeteHaitch** [r-hub/ci-backend#1]
Apologies if this is premature or, indeed, simply out of scope: will it be possible to request that the builder uses the devel branch of Bioconductor (triggered by running `BiocInstaller::useDevel()` before running `BiocInstaller::biocLite()`)? Thanks for your work on this!

**Comment by gaborcsardi** [comment]
Will be fixed at https://github.com/r-hub/rhub/issues/38
